/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package utils;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.junit.jupiter.api.Assertions;

public class UtilsForTests {

	public static void createTestFile(String pathString, String fileContents)
	{
		// Write contents of our test project to new file
		try {
			FileWriter fileWriter = new FileWriter(pathString);
			fileWriter.write(fileContents);
			fileWriter.close();
			
			assertFileExists(pathString);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public static void assertFileExists(String pathString)
	{
		File file = new File(pathString);
		Assertions.assertTrue(file.exists());
	}
	public static void assertFileDoesntExist(String pathString)
	{
		File file = new File(pathString);
		Assertions.assertFalse(file.exists());
	}
	
	public static Date createDate(String strDate, String format)
	{
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat(format);
		Date result = null;
		try {
			result = simpleDateFormat.parse(strDate);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return result;
	}
}
