/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package entityTests;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.richardson.david.entity.gantt.View;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.Unmarshaller;

public class TestEntityView extends TestEntityBase {

	private static String sIMPLE_TASK_TEString = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ 	
			"    <view zooming-state=\"default:11\" id=\"gantt-chart\">\r\n"
			+ "        <field id=\"tpd3\" name=\"Name\" width=\"311\" order=\"0\"/>\r\n"
			+ "        <field id=\"tpd4\" name=\"Begin date\" width=\"84\" order=\"1\"/>\r\n"
			+ "        <field id=\"tpd7\" name=\"Completion\" width=\"34\" order=\"2\"/>\r\n"
			+ "    </view>\r\n"
			+ ""
			;

	@Test
	void test1() {
		View element = null;

		try {
			JAXBContext jaxbContext = JAXBContext.newInstance(View.class);
			Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

			element = (View)unmarshaller.unmarshal(stringToStream(sIMPLE_TASK_TEString));
		}
		catch (Exception e)
		{
			element = null;
			e.printStackTrace();
		}

		Assertions.assertTrue(element != null && element.getId().equals("gantt-chart"));
	}
	

}
