/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package entityTests;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.richardson.david.entity.gantt.TaskProperties;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.Unmarshaller;

public class TestEntityTaskProperties extends TestEntityBase {

	private static String sIMPLE_TASK_TEString = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ 	
			"       <taskproperties>\r\n"
			+ "            <taskproperty id=\"tpd0\" name=\"type\" type=\"default\" valuetype=\"icon\"/>\r\n"
			+ "            <taskproperty id=\"tpd1\" name=\"priority\" type=\"default\" valuetype=\"icon\"/>\r\n"
			+ "            <taskproperty id=\"tpd2\" name=\"info\" type=\"default\" valuetype=\"icon\"/>\r\n"
			+ "            <taskproperty id=\"tpd3\" name=\"name\" type=\"default\" valuetype=\"text\"/>\r\n"
			+ "            <taskproperty id=\"tpd4\" name=\"begindate\" type=\"default\" valuetype=\"date\"/>\r\n"
			+ "            <taskproperty id=\"tpd5\" name=\"enddate\" type=\"default\" valuetype=\"date\"/>\r\n"
			+ "            <taskproperty id=\"tpd6\" name=\"duration\" type=\"default\" valuetype=\"int\"/>\r\n"
			+ "            <taskproperty id=\"tpd7\" name=\"completion\" type=\"default\" valuetype=\"int\"/>\r\n"
			+ "            <taskproperty id=\"tpd8\" name=\"coordinator\" type=\"default\" valuetype=\"text\"/>\r\n"
			+ "            <taskproperty id=\"tpd9\" name=\"predecessorsr\" type=\"default\" valuetype=\"text\"/>\r\n"
			+ "        </taskproperties>\r\n"
			+ ""
			;

	@Test
	void test1() {
		TaskProperties element = null;

		try {
			JAXBContext jaxbContext = JAXBContext.newInstance(TaskProperties.class);
			Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

			element = (TaskProperties)unmarshaller.unmarshal(stringToStream(sIMPLE_TASK_TEString));
		}
		catch (Exception e)
		{
			element = null;
			e.printStackTrace();
		}

		Assertions.assertTrue(element != null);
	}
	

}
