/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package entityTests;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.richardson.david.entity.gantt.Task;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.Unmarshaller;

public class TestEntityTask extends TestEntityBase {

	private static String sIMPLE_TASK_TEString = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ 	
			"<task id=\"44\" name=\"Investigate Redundancy Options for David\" color=\"#8cb6ce\" meeting=\"false\" start=\"2021-12-06\" duration=\"7\" complete=\"0\" thirdDate=\"2021-09-27\" thirdDate-constraint=\"0\" expand=\"true\"/>"
			;

	private static String TASK_WITH_SUB_TASK = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ "<task id=\"16\" name=\"Parent Task\" color=\"#8cb6ce\" meeting=\"false\" start=\"2021-12-06\" duration=\"74\" complete=\"0\" thirdDate=\"2021-11-04\" thirdDate-constraint=\"0\" expand=\"true\">"
			+ "<task id=\"44\" name=\"Sub Task 1\" color=\"#8cb6ce\" meeting=\"false\" start=\"2021-12-06\" duration=\"7\" complete=\"0\" thirdDate=\"2021-09-27\" thirdDate-constraint=\"0\" expand=\"true\"/>"
			+ "<task id=\"45\" name=\"Sub Task 2\" color=\"#8cb6ce\" meeting=\"false\" start=\"2021-12-06\" duration=\"7\" complete=\"0\" thirdDate=\"2021-09-27\" thirdDate-constraint=\"0\" expand=\"true\"/>"
			+ "<task id=\"46\" name=\"Sub Task 3\" color=\"#8cb6ce\" meeting=\"false\" start=\"2021-12-06\" duration=\"7\" complete=\"0\" thirdDate=\"2021-09-27\" thirdDate-constraint=\"0\" expand=\"true\"/>"
			+ "</task>"
			;


	@Test
	void test1() {
		Task element = null;

		try {
			JAXBContext jaxbContext = JAXBContext.newInstance(Task.class);
			Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

			element = (Task)unmarshaller.unmarshal(stringToStream(sIMPLE_TASK_TEString));
		}
		catch (Exception e)
		{
			element = null;
			e.printStackTrace();
		}

		Assertions.assertTrue(element != null && element.getId().equals("44"));
	}
	
	@Test
	void test2() {
		Task element = null;

		try {
			JAXBContext jaxbContext = JAXBContext.newInstance(Task.class);
			Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

			element = (Task)unmarshaller.unmarshal(stringToStream(TASK_WITH_SUB_TASK));
		}
		catch (Exception e)
		{
			element = null;
			e.printStackTrace();
		}

		Assertions.assertTrue(element != null && element.getId().equals("16"));
	}
}
