/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package configTests;

import org.junit.jupiter.api.Test;
import org.richardson.david.config.UserConfig;
import controlTests.TestCommandLine;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import org.junit.jupiter.api.Assertions;

public class TestConfig extends TestCommandLine {

	private static Boolean SHOOSHBoolean = true;
	private static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");


	private static Object[][] CONFIG_WEEK_TESTS_1 =
		{				
				// Start date      End date       Current date  Notify?  Notify Dbl
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "03/07/2021",  false,   null,	},
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "04/07/2021",  true,    0.0,     },
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "05/07/2021",  false,   null,    },
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "06/07/2021",  true,    0.25,	},
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "07/07/2021",  true,    0.5,	    },
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "08/07/2021",  false,   null,	},
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "09/07/2021",  true,    0.75,	},
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "10/07/2021",  true,    1.0,	    },
				{ "Week Tests", "04/07/2021",   "10/07/2021",  "11/07/2021",  false,   null,	},

		};

	private static Object[][] CONFIG_MONTH_TESTS_1 =
		{				
				// Start date      End date       Current date  Notify?  Notify Dbl
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "31/01/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "01/02/2021",  true,    0.0,    },
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "02/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "03/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "04/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "05/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "06/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "07/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "08/02/2021",  true,    0.25,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "09/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "10/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "11/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "12/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "13/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "14/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "15/02/2021",  true,    0.5,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "16/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "17/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "18/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "19/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "20/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "21/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "22/02/2021",  true,    0.75,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "23/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "24/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "25/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "26/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "27/02/2021",  false,   null,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "28/02/2021",  true,    1.0,	},
				{ "Month Tests", "01/02/2021",   "28/02/2021",  "01/03/2021",  false,   null,	},

		};

	private static Object[][] CONFIG_MULTI_MONTH_TESTS_1 =
		{				// 8 week duration spanning two months
				// Start date      End date       Current date  Notify?  Notify Dbl
				{"Multi-month tests", "18/08/2021", "11/09/2021", "17/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "18/08/2021", true, 0.00,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "19/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "20/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "21/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "22/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "23/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "24/08/2021", true, 0.25,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "25/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "26/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "27/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "28/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "29/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "30/08/2021", true, 0.50,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "31/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "01/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "02/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "03/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "04/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "05/09/2021", true, 0.75,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "06/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "07/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "08/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "09/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "10/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "11/09/2021", true, 1.00,  },
				{"Multi-month tests", "18/08/2021", "11/09/2021", "12/09/2021", false, null,  },
		};

	private static Object[][] CONFIG_REALLY_LONG_TESTS_1 =
		{				// 8 week duration spanning two months
				// Start date      End date       Current date  Notify?  Notify Dbl
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/08/2021", true, 0.00,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/08/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/09/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/10/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/11/2021", true, 0.25,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/11/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/12/2021", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/01/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/02/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/03/2022", true, 0.50,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/03/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/04/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/05/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/06/2022", true, 0.75,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/06/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/07/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "13/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "14/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "15/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "16/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "17/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "18/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "19/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "20/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "21/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "22/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "23/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "24/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "25/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "26/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "27/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "28/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "29/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "30/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "31/08/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "01/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "02/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "03/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "04/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "05/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "06/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "07/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "08/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "09/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "10/09/2022", false, null,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "11/09/2022", true, 1.00,  },
				{"Multi-month tests", "18/08/2021", "11/09/2022", "12/09/2022", false, null,  },

		};
	
	
	private static Object[][] CONFIG_SPAN_MULTI_YEAR_TESTS_1 =
		{				// 8 week duration spanning two months
				// Start date      End date       Current date  Notify?  Notify Dbl
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/09/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/09/2021", true, 0.00,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "31/10/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/11/2021", true, 0.25,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/11/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "31/12/2021", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/01/2022", true, 0.50,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "31/01/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/02/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/03/2022", true, 0.75,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "31/03/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "15/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "16/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "17/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "18/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "19/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "20/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "21/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "22/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "23/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "24/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "25/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "26/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "27/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "28/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "29/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "30/04/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "01/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "02/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "03/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "04/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "05/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "06/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "07/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "08/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "09/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "10/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "11/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "12/05/2022", false, null,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "13/05/2022", true, 1.00,  },
				{"Multi-month tests", "30/09/2021", "13/05/2022", "14/05/2022", false, null,  },	
		};
	
	@Test
	void testFile() {
		UserConfig config = getUserConfig();
		assertEquals(config.getCommon().getXmlPath(), "C:\\\\Temp\\\\HouseBuildingSample.gan");		
	}
	@Test
	void testHost() {
		UserConfig config = getUserConfig();		
		assertEquals(config.getCommon().getMail().getSendHost(), "smtp.gmail.com");		
	}
	@Test
	void testPort() {
		UserConfig config = getUserConfig();
		assertEquals(config.getCommon().getMail().getSendPort(), 465L);		
	}
	@Test
	void testUsername() {
		UserConfig config = getUserConfig();
		assertEquals(config.getCommon().getMail().getUsername(), "david@gmail.com");		
	}
	@Test
	void testPassword() {
		UserConfig config = getUserConfig();
		assertEquals(config.getCommon().getMail().getPassword(), "app_password_of_course");		
	}
	@Test
	void testReadHost() {
		UserConfig config = getUserConfig();
		assertEquals(config.getCommon().getMail().getReadHost(), "imap.gmail.com");		
	}
	@Test
	void testRetries() {
		UserConfig config = getUserConfig();
		assertEquals(config.getNotify().getRetries(), 0L);		
	}
	@Test
	void testPrecision() {
		UserConfig config = getUserConfig();
		assertEquals(config.getNotify().getPrecision(), 5);		
	}
	@Test
	void testRepeats() {
		UserConfig config = getUserConfig();

		if (!SHOOSHBoolean)
			System.out.println("testRepeats: " + config.getNotify().getNotifications());
		assertEquals(config.getNotify().getNotifications(), "start 1/4 1/2 3/4 end");		
	}
	@Test
	void testRepeatFractions() {
		UserConfig config = getUserConfig();

		ArrayList<Double> testRes = config.getNotify().getNotificationFractions();

		if (!SHOOSHBoolean)
			System.out.println("testRepeatFractions: " + testRes.size());
		Assertions.assertTrue(testRes.size() == 5);

		Assertions.assertTrue(testRes.contains(0.0));
		Assertions.assertTrue(testRes.contains(0.25));
		Assertions.assertTrue(testRes.contains(0.5));
		Assertions.assertTrue(testRes.contains(0.75));
		Assertions.assertTrue(testRes.contains(1.0));
	}

	@Test
	void testDoRetryMonth() 
	{
		testArray(CONFIG_MONTH_TESTS_1);
	}

	@Test
	void testDoRetryWeek() 
	{
		testArray(CONFIG_WEEK_TESTS_1);
	}
	
	@Test
	void testDoRetryMultiMonth() 
	{
		testArray(CONFIG_MULTI_MONTH_TESTS_1);
	}

	@Test
	void testDoRetryReallyLongTask() 
	{
		testArray(CONFIG_REALLY_LONG_TESTS_1);
	}

	@Test
	void testDoRetrySpanMultiYear() 
	{
		testArray(CONFIG_SPAN_MULTI_YEAR_TESTS_1);
	}

	
	private void testArray(Object[][] array)
	{
		UserConfig config = getUserConfig();

		for (Object[] object : array)
		{
			int i = 0;
			String title      = (String)object[i++];
			Date startDate    = getDate((String)object[i++]);
			Date endDate      = getDate((String)object[i++]);
			Date thisDate     = getDate((String)object[i++]);
			Boolean doNotify  = (Boolean)object[i++];
			Double fracNotify = (Double)object[i++];
			
			String assertString = "From " + startDate + " to " + endDate + " on " + thisDate + " expect " + doNotify + " with frac " + (fracNotify == null ? "null" : fracNotify);

			if (doNotify) Assertions.assertTrue(config.getNotify().doNotification(startDate, endDate, thisDate), assertString);
			else Assertions.assertFalse(config.getNotify().doNotification(startDate, endDate, thisDate), assertString);

			if (fracNotify == null) Assertions.assertTrue(config.getNotify().getFractionForNotification(startDate, endDate, thisDate) == null, assertString);
			else Assertions.assertEquals(config.getNotify().getFractionForNotification(startDate, endDate, thisDate), fracNotify, assertString);

			if (!SHOOSHBoolean)
				System.out.println("Completed: " + title
						+ " start-" + startDate 
						+ " end-" + endDate
						+ " this-" + thisDate
						+ " notify-" + doNotify
						+ " fracNotify-" + (fracNotify == null ? "[null]" : fracNotify));
		}
	}
	private Date getDate(String string) {
		Date result = null;
		try {
			result = DATE_FORMAT.parse(string);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return result;
	}

	private UserConfig getUserConfig()
	{
		resetForTests();
		initializeConfig();
		Assertions.assertTrue(UserConfig.getInstance() != null);
		return UserConfig.getInstance();
	}

	private void assertEquals(String val1, String val2)
	{
		if (!SHOOSHBoolean)
			System.out.println("Comparing \n str1: " + val1 + "\n with \n str2: " + val2);
		Assertions.assertTrue(val1.equals(val2));
	}
	private void assertEquals(Long val1, Long val2)
	{
		if (!SHOOSHBoolean)
			System.out.println("Comparing long1: " + val1 + " with long1: " + val2);
		Assertions.assertTrue(val1.equals(val2));
	}
	private void assertEquals(Integer val1, Integer val2)
	{
		if (!SHOOSHBoolean)
			System.out.println("Comparing int1: " + val1 + " with int2: " + val2);
		Assertions.assertTrue(val1.equals(val2));
	}	
}
