/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package loadTests;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.richardson.david.entity.gantt.Project;
import org.richardson.david.load.DataLoader;
import org.richardson.david.load.DataSaver;
import org.richardson.david.model.Repository;

import controlTests.TestCommandLine;
import emailTests.TestResponseEmailParser;
import utils.ProjectComparator;
import utils.UtilsForTests;

public class TestLoadAndSave {

	//	private static TestResponseEmailParser testResponseEmailParser = new TestResponseEmailParser();
	private static TestResponseEmailParser testResponseEmailParser = new TestResponseEmailParser();


	@Test
	public void testLoadAndSaveAndDelete()
	{		
		DataSaver dataSaver = createDataSaver();
		Assertions.assertTrue(dataSaver != null);
		String backupFileString = dataSaver.getBackupFileName();
		UtilsForTests.assertFileExists(backupFileString);
		compareBackupFileWithOriginal(backupFileString);

		dataSaver.deleteBackup();
		UtilsForTests.assertFileDoesntExist(backupFileString);
	}
	
	@Test
	public void testChangeTaskAndUpdate()
	{
		DataSaver dataSaver = createDataSaver();
		Assertions.assertTrue(dataSaver != null);
		String backupFileString = dataSaver.getBackupFileName();
		UtilsForTests.assertFileExists(backupFileString);
		
		testResponseEmailParser.doTest("half done", false, 50L);
		dataSaver.updateFile();
		dataSaver.deleteBackup();
		UtilsForTests.assertFileDoesntExist(backupFileString);		
	}

	public DataSaver createDataSaver()
	{
		TestCommandLine testCommandLine = new TestCommandLine();		
		DataLoader dataLoader = new DataLoader(testCommandLine.getProjectFilePath());
		Assertions.assertTrue(dataLoader.getProject() != null);
		
		DataSaver dataSaver = new DataSaver(dataLoader);
		String backupFileString = dataSaver.getBackupFileName();
		dataSaver.backupFile();
		UtilsForTests.assertFileExists(backupFileString);
		return dataSaver;
	}
	
	private void compareBackupFileWithOriginal(String backupString)
	{
		DataLoader backupDataLoader = new DataLoader(backupString);
		Project mainProject = Repository.getInstance().getProject();
		Project backProject = backupDataLoader.getProject();
		
		ProjectComparator projectComparator = new ProjectComparator(mainProject, backProject);
		Assertions.assertTrue(projectComparator.areTheySame());		
	}
		
}
