/*
Copyright 2022 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package org.richardson.david.model;

import org.richardson.david.entity.gantt.Depend;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public class EnrichedDepend {
	
	@NonNull private Depend       depend;
	@NonNull private EnrichedTask srcEnrichedTask;
	
	@Getter(lazy=true) private final EnrichedTask destEnrichedTask = initDestEnrichedTask();	

	public String summariseDepend()
	{
		StringBuilder stringBuilder = new StringBuilder();

		stringBuilder.append(""
				+ "Id: " + getDepend().getId()
				+ " Type: " + getDepend().getType()
				+ " Difference: " + getDepend().getDifference()
				+ " Hardness: " + getDepend().getHardness()
				);

		return stringBuilder.toString();
	}
	
	public Boolean expectPredecessorComplete()
	{		
		return getType().equals("FS");
	}
	
	public String getType()
	{
		String resultString = "";
		
		String depTypeString = depend.getType();
		
		resultString = depTypeString.equals("1") ? "SS" : resultString;
		resultString = depTypeString.equals("2") ? "FS" : resultString;
		resultString = depTypeString.equals("3") ? "FF" : resultString;
		resultString = depTypeString.equals("4") ? "SF" : resultString;
		
		return resultString;
	}
	
	private EnrichedTask initDestEnrichedTask()
	{
		EnrichedTask resulTask = Repository.getInstance().getEnrichedTaskHashMap().get(depend.getId());		
		return resulTask;
	}
}
