/*
Copyright 2021 David Richardson, a regular GanttProject User

This file is part of GanttProjectAutomator, a utility conceived from
years of project management experience to make task status communication
just a little bit easier.

It works specifically with files generated by GanttProject, an 
open source project management tool.

GanttProjectAutomator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

GanttProjectAutomator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

See <http://www.gnu.org/licenses/>.
*/
package org.richardson.david.config;

import lombok.Data;

@Data
public class UserConfigUpdate {
	private String  backups = null;
	private Boolean assigneesOnly;
	private String  alertEmail;
	private Boolean includeParentTasks;
	
	@Override
	public String toString()
	{
		StringBuilder sBuilder = new StringBuilder();
				
		sBuilder.append(""
				
				+ "<ul>"
				+ "<li>" + "<b>Backups             :</b> " + getBackups() + "</li>\r\n" 
				+ "<li>" + "<b>Assignees Only      :</b> " + getAssigneesOnly() + "</li>\r\n" 
				+ "<li>" + "<b>Alert Email         :</b> " + getAlertEmail() + "</li>\r\n" 
				+ "<li>" + "<b>Inc Parent Tasks    :</b> " + getIncludeParentTasks() + "</li>\r\n" 
				+ "</ul>"
				);
		
		return sBuilder.toString();
	}

}
